# This is a basic workflow to help you get started with Actions
name: Firebase

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./functions

    strategy:
      matrix:
        node-version: [ 12.x ]
  # This workflow contains a single job called "build"
  main:
    name: Deploy

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install libraries
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: install firebase
        run: npm i firebase-tools -g

      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
